#!/bin/sh

bspc monitor -d TTY WEB LAB MED

# create 4 desktops
#bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# border colors
bspc config active_border_color     "#23edda"
bspc config focused_border_color    "#3b48e3"
bspc config presel_feedback_color   "#f996e2"

# bspc rule -a Navigator desktop="WEB"
#bspc rule -a Spotify desktop='^3'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# make sure everyone is dead
patayin sxhkd
patayin dunst
patayin picom
patayin compton
patayin feh
patayin thunar
patayin xscreensaver
# start apps
# start polybar
$HOME/.config/polybar/launch.sh 
# start sxhkd
sxhkd &
# start notif manager
dunst &
# start File Manager daemon
thunar --daemon &
# enable compton
compton -b --paint-on-overlay --config ~/.config/picom/picom.conf
# set background
feh --bg-fill ~/.wallpapers/snowymountains.jpg & 
# xscreensaver daemon 
xscreensaver -no-splash &
# update pacman mirrorlist
~/scripts/launch_reflector.sh &
