#!/bin/bash

# set environment variables
env \
    XSECURELOCK_AUTH=auth_x11 \
    XSECURELOCK_AUTHPROTO=authproto_pam \
    XSECURELOCK_AUTH_BACKGROUND_COLOR="#263238" \
    XSECURELOCK_AUTH_FOREGROUND_COLOR="#DFDFDF" \
    XSECURELOCK_AUTH_TIMEOUT=60 \
    XSECURELOCK_FONT="Unifont" \
    XSECURELOCK_PASSWORD_PROMPT=disco\
    XSECURELOCK_SAVER=saver_xscreensaver \
    xsecurelock
    #XSECURELOCK_PAM_SERVICE=xscreensaver \
    #XSECURELOCK_NO_COMPOSITE=1 \
    #XSECURELOCK_AUTH_CURSOR_BLINK \
    #XSECURELOCK_AUTH_SOUNDS \
    #XSECURELOCK_AUTH_WARNING_COLOR \
    #XSECURELOCK_BLANK_TIMEOUT=1 \
    #XSECURELOCK_BLANK_DPMS_STATE \
    #XSECURELOCK_BURNIN_MITIGATION \
    #XSECURELOCK_BURNIN_MITIGATION_DYNAMIC \
    #XSECURELOCK_COMPOSITE_OBSCURER \
    #XSECURELOCK_DATETIME_FORMAT \
    #XSECURELOCK_DEBUG_ALLOW_LOCKING_IF_INEFFECTIVE \
    #XSECURELOCK_DEBUG_WINDOW_INFO \
    #XSECURELOCK_DIM_ALPHA=0.5 \
    #XSECURELOCK_DIM_COLOR \
    #XSECURELOCK_DIM_FPS \
    #XSECURELOCK_DIM_MAX_FILL_SIZE \
    #XSECURELOCK_DIM_OVERRIDE_COMPOSITOR_DETECTION \
    #XSECURELOCK_DIM_TIME_MS \
    #XSECURELOCK_DISCARD_FIRST_KEYPRESS \
    #XSECURELOCK_FORCE_GRAB \
    #XSECURELOCK_GLOBAL_SAVER \
    #XSECURELOCK_IDLE_TIMERS \
    #XSECURELOCK_IMAGE_DURATION_SECONDS \
    #XSECURELOCK_KEY_ \
    #XSECURELOCK_LIST_VIDEOS_COMMAND \
    #XSECURELOCK_NO_PAM_RHOST \
    #XSECURELOCK_NO_XRANDR \
    #XSECURELOCK_NO_XRANDR15 \
    #XSECURELOCK_SAVER_RESET_ON_AUTH_CLOSE \
    #XSECURELOCK_SHOW_DATETIME \
    #XSECURELOCK_SHOW_HOSTNAME \
    #XSECURELOCK_SHOW_USERNAME \
    #XSECURELOCK_SINGLE_AUTH_WINDOW \
    #XSECURELOCK_SWITCH_USER_COMMAND \
    #XSECURELOCK_WAIT_TIME_MS \
    #XSECURELOCK_XSCREENSAVER_PATH \
    #XSECURELOCK_XSCREENSAVER_PATH \
